project_id = "xkyuyukppeaencmhakbu"

[functions.send-certificate-email]
verify_jwt = false

[functions.notify-gift-claim]
verify_jwt = false

[functions.parse-rta-statement]
verify_jwt = false

[functions.test-integration]
verify_jwt = true

[functions.generate-blog-post]
verify_jwt = true

[functions.cron-blog-generator]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.generate-market-update]
verify_jwt = true

[functions.cron-market-update]
verify_jwt = false

[functions.generate-academy-content]
verify_jwt = true

[functions.subscribe-newsletter]
verify_jwt = false

[functions.confirm-subscription]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = true

[functions.embed-content]
verify_jwt = true

[functions.embed-content-single]
verify_jwt = false

[functions.chatbot]
verify_jwt = false
