project_id = "xkyuyukppeaencmhakbu"

[functions.send-certificate-email]
verify_jwt = false

[functions.notify-gift-claim]
verify_jwt = false

[functions.parse-rta-statement]
verify_jwt = false

[functions.test-integration]
verify_jwt = true

[functions.generate-blog-post]
verify_jwt = true

[functions.cron-blog-generator]
verify_jwt = false

[functions.sitemap]
verify_jwt = false
