
-- Wipe legacy academy data (no progress yet)
DELETE FROM public.quiz_questions;
DELETE FROM public.learning_chapters;
DELETE FROM public.learning_modules WHERE audience = 'partner';

-- Insert 12 official NISM V-A units
INSERT INTO public.learning_modules
(module_key, slug, title, subtitle, description, audience, cover_emoji, display_order, total_chapters, pass_percentage, issues_certificate, certificate_label, is_published)
VALUES
('investment_landscape',     'investment-landscape',     'Investment Landscape',                       'Unit 1 — Foundation of Indian financial markets',           'Investors and their goals, savings vs investments, asset classes and the risk-return spectrum. Chapters 1–4 of the NISM V-A workbook.', 'partner', '🌍', 1, 4, 70, true, 'NISM V-A · Unit 1', true),
('concept_role_mf',          'concept-role-mf',          'Concept & Role of a Mutual Fund',            'Unit 2 — What a mutual fund is and why it exists',           'How mutual funds pool money, their role in capital formation, and how schemes are classified. Chapters 5–7 of the workbook.',           'partner', '🏦', 2, 3, 70, true, 'NISM V-A · Unit 2', true),
('legal_structure',          'legal-structure',          'Legal Structure of Mutual Funds in India',   'Unit 3 — Sponsor, Trustee, AMC and service providers',       'Three-tier structure, key constituents, RTAs, Custodians, Auditors and the role of SEBI and AMFI. Chapters 8–11 of the workbook.',      'partner', '🏛️', 3, 4, 70, true, 'NISM V-A · Unit 3', true),
('legal_regulatory',         'legal-regulatory',         'Legal & Regulatory Framework',               'Unit 4 — SEBI, AMFI, KYC, PMLA, FATCA and investor protection','Regulatory architecture, investment restrictions, KYC and AML/CFT, FATCA/CRS reporting and grievance redressal. Chapters 12–15.',       'partner', '⚖️', 4, 4, 70, true, 'NISM V-A · Unit 4', true),
('scheme_related_info',      'scheme-related-info',      'Scheme Related Information',                 'Unit 5 — SID, SAI, KIM and the NFO process',                  'Mandatory offer documents, continuous disclosures, NFO timelines and how to read a scheme document. Chapters 16–19.',                   'partner', '📄', 5, 4, 70, true, 'NISM V-A · Unit 5', true),
('fund_distribution',        'fund-distribution',        'Fund Distribution & Channel Management',     'Unit 6 — Channels, ARN/EUIN, commissions and code of conduct','Distribution architecture, registration, trail vs upfront commissions and the AMFI code of conduct. Chapters 20–23.',                   'partner', '🤝', 6, 4, 70, true, 'NISM V-A · Unit 6', true),
('nav_ter_pricing',          'nav-ter-pricing',          'NAV, Total Expense Ratio & Pricing',         'Unit 7 — How NAV is computed and units are priced',           'Daily NAV mechanics, TER slabs and cut-off timings for purchases and redemptions. Chapters 24–26.',                                     'partner', '🧮', 7, 3, 70, true, 'NISM V-A · Unit 7', true),
('taxation',                 'taxation',                 'Taxation of Mutual Funds',                   'Unit 8 — Equity vs debt, IDCW, STT and capital gains',        'How equity, debt and hybrid funds are taxed, treatment of dividends, STT, set-off and carry-forward of capital losses. Chapters 27–29.','partner', '💸', 8, 3, 70, true, 'NISM V-A · Unit 8', true),
('investor_services',        'investor-services',        'Investor Services',                          'Unit 9 — Transactions, SIP/SWP/STP and folio operations',     'Transaction processing, systematic plans, folio mechanics, nominations and grievance routes. Chapters 30–33.',                          'partner', '🧾', 9, 4, 70, true, 'NISM V-A · Unit 9', true),
('risk_return_performance',  'risk-return-performance',  'Risk, Return & Performance of Funds',        'Unit 10 — Measuring returns and risk',                        'Absolute, CAGR and XIRR returns, standard deviation, beta and risk-adjusted measures like Sharpe and Treynor. Chapters 34–36.',         'partner', '📈', 10, 3, 70, true, 'NISM V-A · Unit 10', true),
('scheme_performance',       'scheme-performance',       'Mutual Fund Scheme Performance',             'Unit 11 — Benchmarking and evaluating funds',                 'Benchmarks, factors affecting performance, attribution and how to evaluate a scheme over time. Chapters 37–39.',                        'partner', '🏁', 11, 3, 70, true, 'NISM V-A · Unit 11', true),
('scheme_selection',         'scheme-selection',         'Mutual Fund Scheme Selection',               'Unit 12 — Choosing the right scheme for the client',          'Selection criteria, asset allocation strategies, model portfolios and rebalancing for client goals. Chapters 40–42.',                   'partner', '🎯', 12, 3, 70, true, 'NISM V-A · Unit 12', true);
